export const GET_ACTIVE_ROOM_NAME = 'GET_ACTIVE_ROOM_NAME';
export const GET_ACTIVE_ROOM_KEY = 'GET_ACTIVE_ROOM_KEY';
export const DELETE_ACTIVE_ROOM_NAME = 'DELETE_ACTIVE_ROOM_NAME';
export const DELETE_ACTIVE_ROOM_KEY = 'DELETE_ACTIVE_ROOM_KEY';